import type { Lang } from './data';

export const ui = {
  es: {
    nav: {
      work: 'Proyectos',
      experience: 'Experiencia',
      stack: 'Stack',
      education: 'Formación',
      contact: 'Contacto',
    },
    hero: {
      available: 'Abierto a nuevas oportunidades',
      hello: 'Hola, soy',
      roles: ['Senior Frontend Developer', 'React & Next.js', 'TypeScript', 'Full-stack con NestJS'],
      pitch:
        'Construyo interfaces escalables, rápidas y mantenibles para productos enterprise y SaaS. +{years} años con React, Next.js y TypeScript: monorepos, integración con APIs REST, pagos en tiempo real y una obsesión sana por la calidad del código.',
      ctaWork: 'Ver proyectos',
      ctaCv: 'Descargar CV',
      ctaContact: 'Hablemos',
      stats: {
        years: 'años de experiencia',
        companies: 'empresas',
        projects: 'proyectos',
      },
    },
    impact: {
      title: 'Resultados que he entregado',
      lead: 'Lo que más me importa no es la tecnología, sino el impacto que tiene en el producto.',
    },
    work: {
      title: 'Proyectos seleccionados',
      lead: 'Trabajo para clientes y proyectos personales donde exploro nuevas herramientas.',
      more: 'Más proyectos',
      all: 'Todos',
      kinds: {
        fullstack: 'Full-stack',
        ai: 'IA',
        client: 'Clientes',
        frontend: 'Frontend',
        backend: 'Backend',
        mobile: 'Mobile',
        learning: 'Práctica',
      },
      demo: 'Ver demo',
      code: 'Código',
      featured: 'Destacado',
    },
    experience: {
      title: 'Experiencia',
      lead: 'Equipos de producto enterprise y SaaS donde he pasado de frontend a full-stack y a liderar el proceso.',
      present: 'Actualidad',
    },
    stack: {
      title: 'Stack',
      lead: 'Herramientas con las que trabajo a diario y en producción.',
      how: 'Cómo trabajo',
      howLead:
        'Además de escribir código he liderado equipos como Project Manager: planifico sprints, hago code reviews y pair programming, y automatizo la calidad con Husky + ESLint para que lo que llega a producción funcione.',
    },
    education: {
      title: 'Formación',
      lead: 'Base académica y aprendizaje continuo.',
      degree: 'Título',
      tech: 'Técnicos',
      english: 'Inglés',
      showAll: 'Ver todos',
      showLess: 'Ver menos',
    },
    contact: {
      title: '¿Construimos algo juntos?',
      lead: 'Si tienes un proyecto, una vacante o simplemente quieres conversar, escríbeme. Respondo rápido.',
      direct: 'Canales directos',
      name: 'Nombre',
      email: 'Correo',
      message: 'Mensaje',
      placeholder: 'Cuéntame sobre tu proyecto…',
      send: 'Enviar mensaje',
      sending: 'Enviando…',
      success: '¡Mensaje enviado! Te responderé pronto.',
      error: 'No se pudo enviar. Escríbeme directamente a {email}.',
      copy: 'Copiar correo',
      copied: 'Correo copiado',
    },
    footer: {
      built: 'Diseñado y desarrollado por',
      top: 'Volver arriba',
    },
  },
  en: {
    nav: {
      work: 'Work',
      experience: 'Experience',
      stack: 'Stack',
      education: 'Education',
      contact: 'Contact',
    },
    hero: {
      available: 'Open to new opportunities',
      hello: "Hi, I'm",
      roles: ['Senior Frontend Developer', 'React & Next.js', 'TypeScript', 'Full-stack with NestJS'],
      pitch:
        'I build scalable, fast and maintainable interfaces for enterprise and SaaS products. {years}+ years with React, Next.js and TypeScript: monorepos, REST API integration, real-time payments and a healthy obsession with code quality.',
      ctaWork: 'See my work',
      ctaCv: 'Download CV',
      ctaContact: "Let's talk",
      stats: {
        years: 'years of experience',
        companies: 'companies',
        projects: 'projects',
      },
    },
    impact: {
      title: 'Results I have delivered',
      lead: 'What matters most to me is not the tech itself, but the impact it has on the product.',
    },
    work: {
      title: 'Selected work',
      lead: 'Client work and personal projects where I explore new tools.',
      more: 'More projects',
      all: 'All',
      kinds: {
        fullstack: 'Full-stack',
        ai: 'AI',
        client: 'Clients',
        frontend: 'Frontend',
        backend: 'Backend',
        mobile: 'Mobile',
        learning: 'Practice',
      },
      demo: 'Live demo',
      code: 'Code',
      featured: 'Featured',
    },
    experience: {
      title: 'Experience',
      lead: 'Enterprise and SaaS product teams where I went from frontend to full-stack to leading the process.',
      present: 'Present',
    },
    stack: {
      title: 'Stack',
      lead: 'Tools I use daily and in production.',
      how: 'How I work',
      howLead:
        'Beyond writing code, I have led teams as a Project Manager: planning sprints, running code reviews and pair programming, and automating quality with Husky + ESLint so what reaches production works.',
    },
    education: {
      title: 'Education',
      lead: 'Academic foundation and continuous learning.',
      degree: 'Degree',
      tech: 'Technical',
      english: 'English',
      showAll: 'Show all',
      showLess: 'Show less',
    },
    contact: {
      title: "Let's build something together",
      lead: "Whether it's a project, a role or just a chat, drop me a line. I reply quickly.",
      direct: 'Direct channels',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      placeholder: 'Tell me about your project…',
      send: 'Send message',
      sending: 'Sending…',
      success: 'Message sent! I will get back to you soon.',
      error: "Couldn't send it. Please email me directly at {email}.",
      copy: 'Copy email',
      copied: 'Email copied',
    },
    footer: {
      built: 'Designed & built by',
      top: 'Back to top',
    },
  },
} satisfies Record<Lang, unknown>;

export type UI = (typeof ui)['es'];
